services:
  qbhive:
    image: ghcr.io/felix2yu/qbhive:latest
    container_name: qbhive
    restart: unless-stopped
    pull_policy: always
    ports:
      - "8088:8088"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
    networks:
      - torrent-net

networks:
  torrent-net:
